name: sate_social
description: Sate Social project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  built_value: ^8.5.0
  cloud_firestore: ^4.15.5
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.1.4
  equatable: ^2.0.5
  file_picker: ^5.5.0
  firebase_auth: ^4.10.1
  firebase_analytics: ^10.8.6
  firebase_messaging: ^14.7.18
  firebase_core: 2.26.0
  firebase_storage: ^11.6.6
  flex_seed_scheme: ^1.3.0
  flutter_bloc: ^8.1.2
  flutter_material_pickers: ^3.1.2
  flutter_selfie_liveness: ^1.0.18
  flutter_local_notifications: ^17.0.0
  flutter_progress_hud: ^2.0.2
  fpdart: ^0.6.0
  get: ^4.6.5
  timeago: ^3.6.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.5.3
  intl: ^0.18.0
  network_image_mock: ^2.1.1
  package_info_plus: ^5.0.1
  path: ^1.9.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  built_value_generator: ^8.5.0
  flutter_lints: ^2.0.0
  mockito: ^5.4.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - assets/image/
     - assets/image_groups/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
